name: ProteinDT
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - networkx
  - scikit-learn
  - pytorch::pytorch=1.10
  - transformers
  - lxml
  - lmdb # for TAPE
  - seqeval
  - openai # for baseline ChatGPT
  - accelerate # for baseline Galactica
  - matplotlib # for visualization
  - h5py # for binding editing
  - biopython
  - pyg::pyg=2.0
  - pyg::pytorch-scatter
  - pyg::pytorch-sparse
  - pyg::pytorch-cluster
  - dm-tree # for ESM folding
  - omegaconf
  - ml-collections
  - einops
  - mdtraj
  - pip:
      - fair-esm[esmfold]==2.0.0 # for ESM folding
      - git+https://github.com/NVIDIA/dllogger@0540a43971f4a8a16693a9de9de73c1072020769
#      - git+https://github.com/aqlaboratory/openfold@4b41059694619831a7db195b7e0988fc4ff3a307
